version: "3.9"
services:
    postgres:
        container_name: pg_container_tflic
        image: postgres:latest
        environment:
            POSTGRES_DB: "tflic-dev"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
            - ./service/db-data/:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d tflic-dev"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
        networks:
            - postgres_network
    
    pgadmin:
        container_name: pgadmin_container_tflic
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.org"
            PGADMIN_DEFAULT_PASSWORD: "admin"
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - ./service/pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 256M
        networks:
            - postgres_network

networks:
    postgres_network:
        driver: bridge
